controller_list:
  - name: fake_robot_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_EE_controller
    joints:
      - joint6