# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -3.49
    max_position: 3.49
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 2
  joint2:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 2
  joint3:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 2
  joint4:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 0.85
    has_acceleration_limits: true
    max_acceleration: 2
  joint5:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.85
    has_acceleration_limits: true
    max_acceleration: 2
  joint6:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 0.85
    has_acceleration_limits: true
    max_acceleration: 2
