redhawk/redhawk_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  constraints:
    goal_time: 100.0
    joint1:
      goal: 0.05
    joint2:
      goal: 0.05
    joint3:
      goal: 0.05
    joint4:
      goal: 0.05
    joint5:
      goal: 0.05
    joint6:
      goal: 0.05

